services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/app
    networks:
      - neo4j_network
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
      - ./.neo4j/plugins:/plugins
      - ./.neo4j/import:/var/lib/neo4j/import
    networks:
      - neo4j_network
networks:
  neo4j_network:
    external: false